# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba852cbe082b67da32dd01e1ec4f99cc17147b78d39f3441519b4b5f29b57ec2475e601995a4ee82b3a8bab6d34ee3a26cf2e699dc38f7de81ede93e3173cc8

test:
  secret_key_base: 5140f3eedccfe2afb0af171ed416932777ba2b8cffb89e028514b218654fa395f7f84029c806bd7fcfb1d8d4a037ec21aeb7a750673ad120e6c30a7dd8f28330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
